//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyMathService")]
public interface IMyMathService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Add", ReplyAction="http://tempuri.org/IMyMathService/AddResponse")]
    double Add(double p_firstNnumber, double p_SecondNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Add", ReplyAction="http://tempuri.org/IMyMathService/AddResponse")]
    System.Threading.Tasks.Task<double> AddAsync(double p_firstNnumber, double p_SecondNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Substract", ReplyAction="http://tempuri.org/IMyMathService/SubstractResponse")]
    double Substract(double p_firstNnumber, double p_SecondNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyMathService/Substract", ReplyAction="http://tempuri.org/IMyMathService/SubstractResponse")]
    System.Threading.Tasks.Task<double> SubstractAsync(double p_firstNnumber, double p_SecondNumber);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyMathServiceChannel : IMyMathService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyMathServiceClient : System.ServiceModel.ClientBase<IMyMathService>, IMyMathService
{
    
    public MyMathServiceClient()
    {
    }
    
    public MyMathServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyMathServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyMathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyMathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double Add(double p_firstNnumber, double p_SecondNumber)
    {
        return base.Channel.Add(p_firstNnumber, p_SecondNumber);
    }
    
    public System.Threading.Tasks.Task<double> AddAsync(double p_firstNnumber, double p_SecondNumber)
    {
        return base.Channel.AddAsync(p_firstNnumber, p_SecondNumber);
    }
    
    public double Substract(double p_firstNnumber, double p_SecondNumber)
    {
        return base.Channel.Substract(p_firstNnumber, p_SecondNumber);
    }
    
    public System.Threading.Tasks.Task<double> SubstractAsync(double p_firstNnumber, double p_SecondNumber)
    {
        return base.Channel.SubstractAsync(p_firstNnumber, p_SecondNumber);
    }
}
